"""empty message

Revision ID: 86d9102e9b36
Revises: b54815e82f61
Create Date: 2024-03-18 02:30:06.892709

"""
from typing import Sequence, Union

import fastapi_users_db_sqlalchemy
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "86d9102e9b36"
down_revision: Union[str, None] = "b54815e82f61"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("hosted_ml_models", "cloudwatch_log_group_name")
    op.drop_column("hosted_ml_models", "cloudwatch_log_stream_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "hosted_ml_models",
        sa.Column(
            "cloudwatch_log_stream_name",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "hosted_ml_models",
        sa.Column(
            "cloudwatch_log_group_name",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
