"""empty message

Revision ID: fbbeca8cc243
Revises: 9ffe554168f2
Create Date: 2024-03-05 18:28:16.456833

"""
from typing import Sequence, Union

import fastapi_users_db_sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fbbeca8cc243"
down_revision: Union[str, None] = "9ffe554168f2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ml_model",
        sa.Column(
            "ml_model_metric_limits",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
    )
    op.add_column(
        "ml_model", sa.Column("latest_deployed_version", sa.Integer(), nullable=True)
    )
    op.drop_column("ml_model", "ml_model_minimum_metrics")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ml_model",
        sa.Column(
            "ml_model_minimum_metrics",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("ml_model", "latest_deployed_version")
    op.drop_column("ml_model", "ml_model_metric_limits")
    # ### end Alembic commands ###
