"""empty message

Revision ID: 8a6e2f4ad5db
Revises: 36e7de163031
Create Date: 2024-03-02 03:53:55.314188

"""
from typing import Sequence, Union

import fastapi_users_db_sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8a6e2f4ad5db"
down_revision: Union[str, None] = "36e7de163031"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ml_model",
        sa.Column(
            "ml_model_minimum_metrics",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
    )
    op.add_column(
        "ml_model_versions", sa.Column("ml_model_id", sa.UUID(), nullable=False)
    )
    op.add_column(
        "ml_model_versions",
        sa.Column(
            "hyper_params", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.add_column(
        "ml_model_versions",
        sa.Column(
            "ml_model_metrics",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
    )
    op.drop_constraint(
        "ml_model_versions_model_id_fkey", "ml_model_versions", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("ml_model_versions_ml_model_id_fkey"),
        "ml_model_versions",
        "ml_model",
        ["ml_model_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("ml_model_versions", "model_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ml_model_versions",
        sa.Column("model_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(
        op.f("ml_model_versions_ml_model_id_fkey"),
        "ml_model_versions",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "ml_model_versions_model_id_fkey",
        "ml_model_versions",
        "ml_model",
        ["model_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("ml_model_versions", "ml_model_metrics")
    op.drop_column("ml_model_versions", "hyper_params")
    op.drop_column("ml_model_versions", "ml_model_id")
    op.drop_column("ml_model", "ml_model_minimum_metrics")
    # ### end Alembic commands ###
