"""empty message

Revision ID: daaced099644
Revises: fbbeca8cc243
Create Date: 2024-03-06 03:41:43.589060

"""
from typing import Sequence, Union

import fastapi_users_db_sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "daaced099644"
down_revision: Union[str, None] = "fbbeca8cc243"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        op.f("hosted_ml_models_user_id_fkey"),
        "hosted_ml_models",
        "all_users",
        ["user_id"],
        ["user_id"],
        ondelete="CASCADE",
    )
    op.alter_column(
        "ml_model", "latest_version", existing_type=sa.INTEGER(), nullable=True
    )
    op.add_column(
        "ml_model_versions",
        sa.Column(
            "creation_date",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "ml_model_versions",
        sa.Column(
            "metric_limit_breaches",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
    )
    op.create_foreign_key(
        op.f("ml_model_versions_user_id_fkey"),
        "ml_model_versions",
        "all_users",
        ["user_id"],
        ["user_id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("ml_model_versions_user_id_fkey"), "ml_model_versions", type_="foreignkey"
    )
    op.drop_column("ml_model_versions", "metric_limit_breaches")
    op.drop_column("ml_model_versions", "creation_date")
    op.alter_column(
        "ml_model", "latest_version", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_constraint(
        op.f("hosted_ml_models_user_id_fkey"), "hosted_ml_models", type_="foreignkey"
    )
    # ### end Alembic commands ###
