"""empty message

Revision ID: d3a6a466b2e2
Revises: 392d0806fe1d
Create Date: 2024-02-21 06:00:14.156390

"""
from typing import Sequence, Union

import fastapi_users_db_sqlalchemy
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d3a6a466b2e2"
down_revision: Union[str, None] = "392d0806fe1d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "hosted_ml_models", sa.Column("version", sa.Integer(), nullable=False)
    )
    op.add_column("hosted_ml_models", sa.Column("status", sa.String(), nullable=False))
    op.add_column("hosted_ml_models", sa.Column("reason", sa.String(), nullable=True))
    op.add_column(
        "hosted_ml_models", sa.Column("endpoint_url", sa.String(), nullable=True)
    )
    op.add_column(
        "hosted_ml_models", sa.Column("require_api_key", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "ml_model", sa.Column("require_api_key", sa.Boolean(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ml_model", "require_api_key")
    op.drop_column("hosted_ml_models", "require_api_key")
    op.drop_column("hosted_ml_models", "endpoint_url")
    op.drop_column("hosted_ml_models", "reason")
    op.drop_column("hosted_ml_models", "status")
    op.drop_column("hosted_ml_models", "version")
    # ### end Alembic commands ###
