"""empty message

Revision ID: 24c70242ad73
Revises: 51657e6246ab
Create Date: 2024-03-10 03:34:43.715010

"""
from typing import Sequence, Union

import fastapi_users_db_sqlalchemy
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "24c70242ad73"
down_revision: Union[str, None] = "51657e6246ab"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ml_model", "scheduling_expression_string")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ml_model",
        sa.Column(
            "scheduling_expression_string",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
