"""empty message

Revision ID: 22e737301c91
Revises: d867529a069c
Create Date: 2024-03-16 00:46:44.589912

"""
from typing import Sequence, Union

import fastapi_users_db_sqlalchemy
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "22e737301c91"
down_revision: Union[str, None] = "d867529a069c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ml_model_training_jobs",
        sa.Column("ecs_cluster_arn", sa.String(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ml_model_training_jobs", "ecs_cluster_arn")
    # ### end Alembic commands ###
