"""empty message

Revision ID: 346655895d40
Revises: 61a5ca95d2b6
Create Date: 2024-03-20 04:23:34.581164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '346655895d40'
down_revision: Union[str, None] = '61a5ca95d2b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('hosted_ml_models_load_balancer_id_fkey', 'hosted_ml_models', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('hosted_ml_models_load_balancer_id_fkey', 'hosted_ml_models', 'org_load_balancers', ['load_balancer_id'], ['id'])
    # ### end Alembic commands ###
