"""empty message

Revision ID: 10bf5a7498f8
Revises: 0d4a6478d2f9
Create Date: 2024-02-16 18:26:35.464134

"""
from typing import Sequence, Union

import fastapi_users_db_sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "10bf5a7498f8"
down_revision: Union[str, None] = "0d4a6478d2f9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ml_model",
        sa.Column(
            "ml_model_inputs", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.add_column(
        "ml_model", sa.Column("ml_prediction_type", sa.String(), nullable=True)
    )
    op.add_column(
        "ml_model",
        sa.Column(
            "ml_model_details", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.add_column(
        "ml_model",
        sa.Column("scheduling_expression_string", sa.String(), nullable=True),
    )
    op.add_column(
        "ml_model",
        sa.Column(
            "versioning", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
    )
    op.add_column(
        "ml_model_training_jobs",
        sa.Column(
            "start_time", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
    )
    op.add_column(
        "ml_model_training_jobs", sa.Column("end_time", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ml_model_training_jobs", "end_time")
    op.drop_column("ml_model_training_jobs", "start_time")
    op.drop_column("ml_model", "versioning")
    op.drop_column("ml_model", "scheduling_expression_string")
    op.drop_column("ml_model", "ml_model_details")
    op.drop_column("ml_model", "ml_prediction_type")
    op.drop_column("ml_model", "ml_model_inputs")
    # ### end Alembic commands ###
