"""empty message

Revision ID: 51657e6246ab
Revises: daaced099644
Create Date: 2024-03-07 19:24:26.520971

"""
from typing import Sequence, Union

import fastapi_users_db_sqlalchemy
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "51657e6246ab"
down_revision: Union[str, None] = "daaced099644"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ml_model", sa.Column("predict_function_name", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ml_model", "predict_function_name")
    # ### end Alembic commands ###
