"""empty message

Revision ID: b54815e82f61
Revises: 22e737301c91
Create Date: 2024-03-18 01:44:42.287602

"""
from typing import Sequence, Union

import fastapi_users_db_sqlalchemy
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b54815e82f61"
down_revision: Union[str, None] = "22e737301c91"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "hosted_ml_models",
        sa.Column("cloudwatch_log_group_name", sa.String(), nullable=True),
    )
    op.add_column(
        "hosted_ml_models",
        sa.Column("cloudwatch_log_stream_name", sa.String(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("hosted_ml_models", "cloudwatch_log_stream_name")
    op.drop_column("hosted_ml_models", "cloudwatch_log_group_name")
    # ### end Alembic commands ###
